### ISSUE TITLE
src/operations/delete_user.cr Avram::BasicOperation went away.

### ISSUE THREAD

**Issue by BrucePerens** [GrottoPress/penny#1]
Meth src/operations/delete_user.cr uses Avram::BasicOperation, which seems to have gone away with the Avram API revamp. I changed it to Avram::Operation.

**Comment by akadusei** [comment]
Yeah. `Avram::BasicOperation` is something *Shield* invented (it never existed in *Avram* itself), mainly to support `.needs` macro in non-database operations. *Avram*'s recent release supports `.needs` natively for non-database operations, so I've removed it from *Shield*.
